### ISSUE TITLE
Редактирование торрента

### ISSUE THREAD

**Issue by Fox-llc** [YouROK/TorrServe#104]
![Screenshot_2024-11-28-06-47-04-73_a87fd7db6caa850b517aa6fa9d2fcd0e.jpg](https://github.com/user-attachments/assets/e9a96d7d-2fb7-48f6-af0a-f965ba1dd452)

В веб интерфейсе можно редактировать торрент, почему это нельзя сделать в нативном приложении torrserve?

**Comment by tsynik** [comment]
потому что веб интерфейс сервера доступен та любом устройстве
