### ISSUE TITLE
Nova Player stopped working with version 1.1.85 + server 1.1.77 

### ISSUE THREAD

**Issue by darkblaze69** [YouROK/TorrServe#28]
Android 10, [Nova Player](https://github.com/nova-video-player/aos-AVP)
Works: 1.1.84 + server 1.1.76
Doesn't work: 1.1.85 + server 1.1.77
Doesn't work: 1.1.85 + server 1.1.76

I saw the issue on https://github.com/nova-video-player/aos-AVP/issues/362 with blaming to http plaintext. But apparently it also doesn't work with valid a https connection (tried a valid letsencrypt cert).

Nova player says  
`http://localhost:8090/torrent/play?link=magnet:?xt=urn:btih:xxxx&dn=Movie+BDRip.1080.mkv&tr=http%3A%2F%2Fsite.org%2Fann&tr=http%3A%2F%2Fretracker.local%2Fannounce&file=0`

**Did not managed to access the file**

As with 1.1.84 + server 1.1.76 it works perfectly seems like something critical changed on torrserve/server update.

**Comment by YouROK** [comment]
Compile api is upgrade and now is not working. This is solved on the player side.
https://stackoverflow.com/a/54827498
