### ISSUE TITLE
Using newer versions of TorrServe + Kodi (both Leia and Matrix) does not allow browsing for external subtitles

### ISSUE THREAD

**Issue by hitmancho** [YouROK/TorrServe#29]
This is an issue that did not appear in older 1.1.* versions (pre-1.1.76 definitely). It is still persistent for both a Philips Smart TV 8.0 and a Beelink GT1 Android TV 9.0 box. Basically, if TorrServe is set up to use an external server (both 1.1.77 and MatriX.83 from your other repo on a Linux-arm7 RPi 4) and Kodi as a player on my multimedia device, Kodi cannot navigate to an external subtitle location at all. It just crashes back to the Android homescreen when trying to browse for subtitle files while the stream is playing.

I did not see this being reported before and it did work at one point, though I cannot confirm how long before 1.1.76, so I was using old releases for a time. Nowadays, I download my subtitles with the OpenSubtitles add-on, but it is still useful to be able to put subtitles in a different language somewhere and browse to it. Delete if this issue is already being looked into or is too much of an edge case to reasonably fix.

**Comment by YouROK** [comment]
This is a problem in server
