### ISSUE TITLE
Возможность добавить торрент файлом

### ISSUE THREAD

**Issue by johnd0e** [YouROK/TorrServe#32]
Сейчас предусмотрено добавление только через магнет-ссылку.

В веб-интерфейсе самого сервера такая возможность есть, отдельным пунктом.
(возможно стоило бы объединить оба варианта в одном пункте)

**Comment by dancheskus** [comment]
Это как раз то, над чем я работал в последнем обновлении. Со следующим релизом будет объединённая кнопка￼, и не только это 😊.

**Comment by tsynik** [comment]
реализовано в MatriX.101+

**Comment by johnd0e** [comment]
@tsynik 
Matrix.110.Client, не вижу возможности загрузить торрент-файл.

**Comment by tsynik** [comment]
По кнопке Добивить в клиенте: 
![ADD](https://user-images.githubusercontent.com/1551446/141128057-677621c4-b255-49c2-90a6-2f0e8f05c4b6.png)
Ну и веб сервера конечно

**Comment by johnd0e** [comment]
В том и дело, что хочется чтобы по отдельной кнопке в клиенте открывался выбор файла.

**Comment by tsynik** [comment]
> В том и дело, что хочется чтобы по отдельной кнопке в клиенте открывался выбор файла.

Зачем? Клиент обрабатывает .torrent файлы, то  есть при нажатии на торрент скачанный в андроиде будет диалог предложния откртия его в TorrServe

**Comment by johnd0e** [comment]
Для случая когда торрент не только что скачан, а давно лежит в папке

**Comment by tsynik** [comment]
> Для случая когда торрент не только что скачан, а давно лежит в папке

что это меняет - при выборе его в ОС будет предложение открыть его в том числе в TorrServe. Городить файл-пикер ради дублирования штатных функций imho бессмысленно, тем более что при желании можно без проблем выбрать этот торрент в вебе сервера через браузер.

**Comment by johnd0e** [comment]
Ok
