### ISSUE TITLE
Возможность сохранить плейлист как файл

### ISSUE THREAD

**Issue by johnd0e** [YouROK/TorrServe#33]
Полезно для долгоживущих плейлистов (аудиокниги, музыка).

Кроме того, сталкивался с тем, что: 
- на некоторых системах при запуске плейлиста нужный плеер вообще не предлагатся.
- запуске плейлиста "онлайн" он трактуется иначе: как набор "зеркал" одного и того же потока (как у радиостанций).
Так работает например aimp.

Возможность скачать плейлист помогла бы в этих случаях.

В веб-интерфейсе самого сервера такая возможность есть.

**Comment by YouROK** [comment]
В меню есть кнопка плейлиста, по кнопке отдается ссылка в систему, а там уже кто ее примет того и выведет

**Comment by johnd0e** [comment]
> а там уже кто ее примет того и выведет

С выводом нет проблем, вопрос в том чтобы сохранить как файл.
Для себя решил вопрос с помощью https://play.google.com/store/apps/details?id=com.fooview.android.fooview&hl=ru&gl=US
