### ISSUE TITLE
Возможность оперативно пропустить предварительную буферизацию

### ISSUE THREAD

**Issue by johnd0e** [YouROK/TorrServe#34]
Существует настройка сервера, определяющая размер буфера, однако хотелось бы иметь возможность иногда пропускать  этот этап.

Имеет смысл например в таком сценарии: обычно я смотрю фильмы, и предварительное кэширование/буферизация меня полностью устраивает.

Но иногда я запускаю музыку, для которой (а) большой буфер не нужен, и (б) скорость его наполнения может оказаться черепашьей.

Было бы удобно иметь дополнительную кнопку "пропустить буферизацию".

**Comment by YouROK** [comment]
Убрал в сервере минимальный буфер
