### ISSUE TITLE
настройки и пояснение

### ISSUE THREAD

**Issue by MaximKiselev** [YouROK/TorrServe#35]
привет. спасибо за крутую тулзу. 
у меня пару вопросов возникло по настройке.
1. откуда берутся значения по умолчанию - например размер кеша. те тулза мониторит сама скок брать например 10 процентов от свободной памяти или как - имееться ввиду первоначальные настройки после запуска?
2. что такое буфер предварительной загрузки - насколько понял - это опция говорит когда начать проигрывание. те при 20% буфера - заполненность кеша в 100 мб будет 20 мб. так ли это ? и сам размер будет входить в общий уже скаченный кеш.
3. что такое опережающий кеш. это как доп место к другому. те если кеш 100 а опережающий кеш 100 процентов. то всего будет резервироваться 200 мб рам памяти?

**Comment by tsynik** [comment]
в вебе сервера в Настройках есть графическое представление распределения кеша. 1. подобраны на основе статистики использования 2. Да, но не менее 32МБ 3. процент от основного - 100% = 100МБ

**Comment by MaximKiselev** [comment]
> в вебе сервера в Настройках есть графическое представление распределения кеша. 1. подобраны на основе статистики использования 2. Да, но не менее 32МБ 3. процент от основного - 100% = 100МБ

привет. про последнее не понял.  те если скажем кеш 100 мб. а опережающий кеш 100 процентов. то скок рама всего будет использоваться? 200 мб

**Comment by tsynik** [comment]
При кеше в 200 МБ и 100% опережающего кеша будет использоваться 200МБ (по факту больше) и все 200МБ будут перед позицией воспроизведения. При 50% - 100 МБ до и 100 МБ после. При нуле соотвественно перед позицией будет один или два блока.

**Comment by MaximKiselev** [comment]
@tsynik ок. спасибо.
