### ISSUE TITLE
Возможность скачивать файлы

### ISSUE THREAD

**Issue by iterprise** [YouROK/TorrServe#37]
Сейчас есть только возможность добавить в плейлист. 
Почему не добавить возможность скачивать файлы, те сделать выбор "смотреть" и "скачать".

**Comment by YouROK** [comment]
Программа сделана для просмотра онлайн. Скачать файлы можно самому по ссылке, либо другой программой

**Comment by iterprise** [comment]
Да, я понимаю. Но например я хочу посмотреть фильм сейчас и посмотреть его еще раз позже, это было бы удобной функцией. И добавление еще одной программы добавляет неудобства с выбором то одного торрент клиента, то другого. 
Если втает вопрос, что меню выбора действия становится слишком грамозким, можно сделать его кастомизируемым.

**Comment by YouROK** [comment]
Слишком много всего переделывать, нужно логику сопоставления торрентов делать, по мимо работы и обработки файлов. Это нужно сделать обычную качалку торрентов, но программа нужна не для закачки, а для онлайн. Проще включить закачку последовательно и смотреть там

**Comment by iterprise** [comment]
Тогда возможно проще добавить возможно в меню действия "открыть сторонним клиентом", было бы тоже приемлемо.

**Comment by YouROK** [comment]
Уже есть, поделиться называется

**Comment by iterprise** [comment]
Есть возможность вынести ее в меню выбора действия? хотябы опционально. В любом случае спасибо за хороший продукт.

**Comment by YouROK** [comment]
Это то меню, которое при выборе торрентов? Зачем, андроид сам регулирует такие действия. Установили программы, которые работают с магнитами, они и будут в первую очередь выскакивать при действиях с торрентами. Зачем делать двойную прокладку?

**Comment by iterprise** [comment]
Чтобы сделать действие как можно проще, для людей которые не разбираются. Андроид предлагает "открыть один раз" или "открывать всегда" могут появится лишнии приложения в списке, а не один нужны торрент клиент. Одним словом это не для нас с вами, а скажим для пожилиых людей, у меня желание сделать как можно проще.
