### ISSUE TITLE
Локальный сервер для NUM

### ISSUE THREAD

**Issue by iboxmpos** [YouROK/TorrServe#38]
Огромная просьба адаптировать функционал локального сервера TorrServe для NUM в целях поддержки синхронизации настроек, избранного и истории просмотров NUM для устройств в переделах локальной сети. Заранее благодарю!

**Comment by YouROK** [comment]
Торрсерв это другая программа, через нее точно не будет ни какой синхронизации, для других прог. А вот самой синхронизации на нум подумаю

**Comment by iboxmpos** [comment]
Прошу прощения за ошибку с местом формирования запроса - не нашел issues для num(

Заранее премного благодарен за рассмотрение идеи по синхронизации.
