### ISSUE TITLE
F-Droid

### ISSUE THREAD

**Issue by x13a** [YouROK/TorrServe#45]
Hi,

To publish app on [F-Droid](https://www.f-droid.org/) it has to be `FOSS`, without Google Services, analytics and ADs. Can we make `foss` branch to be compatible with F-Droid rules?

```sh
~/tmp
❯ rg firebase ./TorrServe
./TorrServe/build.gradle
13:        classpath 'com.google.firebase:firebase-crashlytics-gradle:2.7.1'

./TorrServe/app/google-services.json
4:    "firebase_url": "https://torrserve.firebaseio.com",

./TorrServe/app/build.gradle
4:    id 'com.google.firebase.crashlytics'
71:    // firebase
72:    implementation 'com.google.firebase:firebase-core:19.0.2'
73:    implementation 'com.google.firebase:firebase-crashlytics:18.2.3'
88:apply plugin: 'com.google.firebase.crashlytics'

./TorrServe/app/src/main/java/ru/yourok/torrserve/ui/activities/main/MainActivity.kt
14:import com.google.firebase.analytics.FirebaseAnalytics
44:    private var firebaseAnalytics: FirebaseAnalytics? = null
51:        firebaseAnalytics = FirebaseAnalytics.getInstance(this)

./TorrServe/app/src/main/java/ru/yourok/torrserve/ui/activities/play/PlayActivity.kt
10:import com.google.firebase.analytics.FirebaseAnalytics
40:    private var firebaseAnalytics: FirebaseAnalytics? = null
56:        firebaseAnalytics = FirebaseAnalytics.getInstance(this)

./TorrServe/app/src/main/java/ru/yourok/torrserve/ad/AD.kt
10:import com.google.firebase.analytics.FirebaseAnalytics

~/tmp
❯ rg gms ./TorrServe
./TorrServe/build.gradle
12:        classpath 'com.google.gms:google-services:4.3.10'

./TorrServe/app/build.gradle
87:apply plugin: 'com.google.gms.google-services'
```

**Comment by YouROK** [comment]
Я могу добавить тебя в контрибьютеры, если есть желание вести ветку без аналитики

**Comment by x13a** [comment]
Спасибо, не надо. Создай `foss-master` ветку, а я в неё сделаю pull.

**Comment by x13a** [comment]
Поставь пожалуйста тэг с версией на `foss-master` ветку, чтобы можно было создать пул реквест в F-Droid.

**Comment by tsynik** [comment]
> Поставь пожалуйста тэг с версией на `foss-master` ветку, чтобы можно было создать пул реквест в F-Droid.

done - https://github.com/YouROK/TorrServe/releases/tag/MatriX.110.F-Droid

**Comment by x13a** [comment]
Придётся перетэговать, забыл про лицензию :(

**Comment by YouROK** [comment]
Добавил лицензию

**Comment by x13a** [comment]
Передвиньте пожалуйста тэг `MatriX.110.F-Droid`, чтобы лицензия была включена. Спасибо

**Comment by YouROK** [comment]
> Передвиньте пожалуйста тэг `MatriX.110.F-Droid`, чтобы лицензия была включена. Спасибо

На гитхабе можно как-то сделать тэг для ветки через сайт?

**Comment by x13a** [comment]
Не уверен, этот тэг у меня только в клиенте показывает.

**Comment by x13a** [comment]
@tsynik , my friend, all hopes on you.. 

Need to retag recent commit on `foss-master` branch for F-Droid.

**Comment by tsynik** [comment]
> Need to retag recent commit on `foss-master` branch for F-Droid.

done

**Comment by x13a** [comment]
MR: [10069](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/10069)

**Comment by x13a** [comment]
Merged !

**Comment by tsynik** [comment]
Because foss branch is different, and app code too
