### ISSUE TITLE
Оперативная индикация качества соединения для проигрываемого файла

### ISSUE THREAD

**Issue by johnd0e** [YouROK/TorrServe#47]
Не каждый торрент может обеспечить качество соединения, достаточное для проигрывания.
Ранее это легко было оценить на этапе буферизации, где в окошке отображаются все нужные параметры.
С другой стороны, буферизация тоже иногда неоправданно затягивалась, что было исправлено (#34).

Однако теперь без предварительной буферизации сложно оценить параметры соединения, и неясно то ли надо подождать немного, то ли торрент скорее мёртв, и надо искать другой.

Предлагаю возможные решения:
- (проще) Для оценки соединения можно использовать окошко информации при буферизации, однако крайне желательно предусотреть возможность в определённый момент принудительнор закончить её, и перейти к просмотру.
- (сложнее) После начала воспроизведения в плеере выводиить поверх него своё окошко информации, наприме до достижения определённой скорости.

**Comment by YouROK** [comment]
Окно буферизации доступно как и раньше
