### ISSUE TITLE
URL сервера без порта

### ISSUE THREAD

**Issue by alehano** [YouROK/TorrServe#63]
При попытке добавить в URL сервера доменное имя, при сохранении добавляется порт 8090, даже если он не был указан. Пожалуйста, исправьте баг.

**Comment by tsynik** [comment]
> При попытке добавить в URL сервера доменное имя, при сохранении добавляется порт 8090, даже если он не был указан. Пожалуйста, исправьте баг.

Это не баг - без указания порта подставляется порт по умолчанию (и это порт 8090). Для добавления url с нестандартным портом нужно его указывать - http://xyz.link:80
