### ISSUE TITLE
Включив кэш с диска и поменяв локацию кэша приложение падает

### ISSUE THREAD

**Issue by holms** [YouROK/TorrServe#67]
Дело произходит на miTV боксе 

    Иду в настройки,
    Указываю использовать кэш с диска
    Указываю путь к кэшу
        нахожу директорию где хочу хранить кэш
        создаю новую директорию,
        печают ее название, enter, и крэш

Версия Matrix.117.Client

**Comment by tsynik** [comment]
Не возможно воспроизвести
