### ISSUE TITLE
DLNA server problem

### ISSUE THREAD

**Issue by rutkas** [YouROK/TorrServe#69]
I have tried DLNA (upnp) server feature and noticed that external media box does not see any torrents, the last element in upnp tree that it reaches us "torrents" folder that is empty.

When I'm trying to browse upnp with VLC from laptop I can see the list of torrents, but not able to go inside of torrent (playlist) and can't see the list of files (streams) in the playlist. Can only play entire playlist. That is not correct, cause there's no ability to select exact file to play. And I think this problem is related to the problem with hd media box that can not see enything in torrents at all.

Looks like a problem with mime types or structuring the data for dlna.

When I start some dlna service in media player giving it playlists from torrserver, it is able to create correct tree (for example with xupnpd).

It also could be good to have an option to configure dlna/upnp server including ability to configure mime-types, upnp protocols, etc.  That is sometimes needed to make specific hd boxes work correctly with it.

**Comment by tsynik** [comment]
PRs are welcome. VLC tested and can browse torrents from TorrServer DLNA, and load files list from them. Anyway, here it's closed because it's not the feature of TorrServe

**Comment by rutkas** [comment]
VLC can browse only torrents, but cannot browse files inside torrent. If torrent includes a season of the TV show that has several file, you cannot browse and switch between this files. Playback can only be started from the first file in torrent's playlist.

**Comment by tsynik** [comment]
> VLC can browse only torrents, but cannot browse files inside torrent. If torrent includes a season of the TV show that has several file, you cannot browse and switch between this files. Playback can only be started from the first file in torrent's playlist.

![2023-03-29 15 20 42](https://user-images.githubusercontent.com/1551446/228533617-b57cb85e-f7c5-4d51-90d8-22ea83ffb952.jpg)
![2023-03-29 15 20 36](https://user-images.githubusercontent.com/1551446/228533623-707ee53a-ffeb-424e-8b3c-bf4d6029a747.jpg)
![2023-03-29 15 20 27](https://user-images.githubusercontent.com/1551446/228533627-0a1e4b14-29e6-49b9-89a2-2249d9ebecb1.jpg)

It's VLC and it have no issues on series torrent files browse

**Comment by rutkas** [comment]
Sorry for not mentioning, I was talking about VLC for Windows. Here is screenshot from it.
In top is xuPNPd dlna server that shows content of same playlist. Playlist from torreserve was uploaded to that dlna server, and it is ok there.
At bottom is torrserver dlna (called xbyte-torrserve), that plays only first track from this torrent and do not show playlist content.

![2023-03-29](https://user-images.githubusercontent.com/14265370/228612819-90ae81dc-66c3-4ab0-885e-7a18dc828ef7.png)

**Comment by tsynik** [comment]
> Sorry for not mentioning, I was talking about VLC for Windows. Here is screenshot from it.
> In top is xuPNPd dlna server that shows content of same playlist. Playlist from torreserve was uploaded to that dlna server, and it is ok there.
> At bottom is torrserver dlna (called xbyte-torrserve), that plays only first track from this torrent and do not show playlist content.

UPNP <> DLNA. As I mentioned before DLNA server from TorrServe works for VLC on Android as expected, and there is no any playlists at all in TorrServer DLNA implementation.

**Comment by rutkas** [comment]
xbyte-torrserve is a uPnP resource

![image](https://user-images.githubusercontent.com/14265370/228700278-be58df5f-d85c-4840-92bc-5282b0f87a10.png)

Then I noticed strange things. I have installed VLC on ios. It could not show content for thi exact torrent. Then I tried another torrents with vlc ios and  it displayed "Load torrent", and after that these another torrents begant to display on VLC Winows. But this one torrent is still not showing not in ios not in windows.
And torrents list is not showing in hd media box on linux in uPnP from torrserve source at all. I will continue investigating.

**Comment by tsynik** [comment]
> Then I noticed strange things. I have installed VLC on ios. It could not show content for thi exact torrent. Then I tried another torrents with vlc ios and it displayed "Load torrent", and after that these another torrents begant to display on VLC Winows. But this one torrent is still not showing not in ios not in windows.
> And torrents list is not showing in hd media box on linux in uPnP from torrserve source at all. I will continue investigating.

It's expected behavior. TorrServer store not data but torrents (links, magnets, hashes etc). If some of them can't be loaded from seeders it will not show any content for them. That's the reason there is Load Torrent button - it request torrent data from peers for that torrent and populate dlna-compatible file list on receive actual torrent content.
