### ISSUE TITLE
Запрос на добавление элемента управления

### ISSUE THREAD

**Issue by YoshiKill** [YouROK/TorrServe#71]
Приветствую, хотел бы попросить добавить в клиент возможность вызывать меню не только свайпом от левого края, а то выходит патовая ситуация если установлено управление жестами, этот свайп уже занят на функцию назад, и выходит что меню невозможно никак вызвать и ты просто выходишь с приложения. По этому было бы хорошо добавить функцию небольшой иконки в каком то углу, при нажатии на которую выезжало бы меню. По желанию для минималистов можно даже сделать возможность включать или выключать эту иконку.

**Comment by tanat74** [comment]
Добрый день.
А в версии приложения с fdroid кнопка меню тоже должна появиться?
Я там не вижу, и не могу пользоваться приложением из-за этого.

**Comment by YoshiKill** [comment]
> Добрый день. А в версии приложения с fdroid кнопка меню тоже должна появиться? Я там не вижу, и не могу пользоваться приложением из-за этого.
Включите кнопки в андроид, зайдите в меню черезе свайп и уже там включите отображение кнопки.
