### ISSUE TITLE
Оптимизация пространства на экране списка файлов

### ISSUE THREAD

**Issue by Omegaplexx** [YouROK/TorrServe#72]
Приветствую! Меня давно мучит не самое удачное расположение элементов на экране списка файлов в горизонтальной ориентации:
![Screenshot_20230401-074720_TorrServe_MatriX](https://user-images.githubusercontent.com/95503207/229266300-430ef14b-fca1-4d5a-b9ae-76164a89a108.png)
Не могли бы Вы, пожалуйста, сократить пустое пространство между кнопками и информацией о торренте? При наличии постера пустоты становится ещё больше, а окошко с выбором эпизода становится крошечным. Ещё я бы хотел, чтобы затенение сверху и снизу элементов списка не было таким широким, ведь оно дополнительно сокращает зону видимости. Нельзя ли затенение тоже сократить (не в ущерб дизайну)? А то из-за него даже 3 серию не видно полностью.

Может быть, для альбомной ориентации удобнее было бы сделать макет, подобный этому?
![Screenshot_20230401-080914_TorrServe_MatriX](https://user-images.githubusercontent.com/95503207/229266818-210f0bda-43bd-413e-bdd8-57f1fc0c90cc.png)
Информация о торренте и кнопки «Играть всё», «Продолжить» могли бы находиться слева, а список файлов – справа.

Надеюсь, не обойдёте стороной мою просьбу. Буду ждать ответа :)

**Comment by tsynik** [comment]
Этот диалог уже был оптимизирован в последнем релизе насолько возможно.
