### ISSUE TITLE
Оптимизация пространства в списке файлов

### ISSUE THREAD

**Issue by Sigmas91** [YouROK/TorrServe#73]
![229266300-430ef14b-fca1-4d5a-b9ae-76164a89a108](https://user-images.githubusercontent.com/130466991/232904589-26e4c5fb-c725-426d-8367-6390364c1511.png)
Здравствуйте. Не могли бы вы перенести кнопки "играть всё" и "продолжить" с верхнего положение в бока. Например "играть всё" будет слева, а "продолжить" справа. Это значительно уменьшит время прокрутки списка.

**Comment by tsynik** [comment]
Нет, в данном  диалоге расположение кнопок сбоку не возможно.

**Comment by v1talii-dev** [comment]
@tsynik, а можно сделать так, чтобы фокус был не на текущей серии в списке, а на кнопке "продолжить"? Это бы стало очень полезной фичей при просмотре сериалов с множеством сезонов и избавило бы от утомляющего скролла вверх.

Или может оставить всё как есть, только чтобы плеер запускался в режиме проигрывания следующей серии. По сути по клику на серию запускается "продолжить" (сейчас же плеер сворачивается, как только серия досмотрена).  Может вынести это в отдельную настройку, которая будет по умолчанию выключена?
