### ISSUE TITLE
[FR] Добавить предзагрузку или загрузку на стороне клиента TorrServe

### ISSUE THREAD

**Issue by filimonic** [YouROK/TorrServe#74]
Прошу добавить в TorrServe предзагрузку на стороне клиента.

Ситуация: 
Android TV, 4G интернет в лесной глуши, оператор борется с торрентами и периодически падает.
Есть желание посмотреть фильм "с комфортом".

Текущее решение: TorrServer установлен на VPS ("на домашнем роутере в городе"), а клиент TorrServe к нему подключается и тянет "в один поток", что не триггерит оператора что-либо резать. 

Проблемы: 
1) Вынужден использовать VIMU плеер из-за его встроенной предзагрузки. 
2) Вынужден ставить фильм на паузу чтобы дать VIMU предзагрузить контент.
3) Вынужден полагаться на оператора, что он сможет обеспечить качество канала все 2 часа фильма.

Хотелось бы:
1) Иметь возможность выбрать другой плеер, а предзагрузку отдать на откуп TorrServe
2) Иметь возможность заранее "скачать" через TorrServe данные с TorrServer локально и полностью, чтобы быть уверенным в успешности просмотра фильма и не зависеть от внезапно упавшего LTE в середине фильма.
2.1 - Иметь ограничение скорости полного скачивания (например, закинуть утром торрент в TorrServer, сказать TorrServe-у скачать его со скоростью не больше 1 Мбита\с, спокойно поработать днем, не борясь с забитым каналом, и вечером посмотреть локально загруженный фильм)
2.2 - Иметь возможность указать накопитель для "предзагрузки" для TorrServe - например SD-карту, а не только RAM

**Comment by tsynik** [comment]
Предзагрузка реализована на стороне клиента TorrServe - при старте воспроизведения показывается окно предзагрузки в соотвествии с настройками сервера.

**Comment by filimonic** [comment]
@tsynik Речь не про окно предзагрузки, а про фактическую предзагрузку данных на сторону TorrServe из удаленного TorrServer

**Comment by tsynik** [comment]
> Речь не про окно статуса предзагрузки TorrServer-ом, отображаемое на стороне TorrServe, а про фактическую предзагрузку данных на сторону TorrServe из удаленного TorrServer
предзагрузкой занимается сервер (в кеш) и плеер (в буфер). Клиент же может дать указание серверу предзагрузить кеш, что и делает. В процессе воспроизведения TorrServe не участвует и не будет - это не его задача.

**Comment by filimonic** [comment]
@tsynik Возможно вариант TorrServer который будет выступать кеширующим прокси между "большим" TorrServer и TorrServe?

**Comment by tsynik** [comment]
> Возможно вариант TorrServer который будет выступать кеширующим прокси между "большим" TorrServer и TorrServe?

Еще раз - TorrServe не участвует в воспроизведении никак. Он в принципе не нужен для просмотра и его может не быть. Это менеджер по добавлению и отображению торрентов на сервере и по установке и настройке локального сервера на Android. Вопросы проксирования - к прокси, коих миллион и в них можно настроить что хошь.

**Comment by filimonic** [comment]
@tsynik понял, осознал. Я почему то думал что поток идёт через него
