### ISSUE TITLE
123 doesn't work on Android 4.4.4

### ISSUE THREAD

**Issue by finn1199** [YouROK/TorrServe#76]
123 версия не работает после установки на Телевизоре с Android 4.4.4
При запуске выкидывает сообщение - в Приложении TorrServe MatriX.123.Client произошла ошибка и не открывает и так постоянно.

Откатился на 122 и всё работает (предыдущие версии все прекрасно устанавливались и работали)

**Comment by tsynik** [comment]
> 123 версия не работает после установки на Телевизоре с Android 4.4.4
> При запуске выкидывает сообщение - в Приложении TorrServe MatriX.123.Client произошла ошибка и не открывает и так постоянно.

Исправлено в ветке master и 123 релизе для f-droid - https://f-droid.org/ru/packages/ru.yourok.torrserve/
