### ISSUE TITLE
Disable automatically adding port number in end of server host link

### ISSUE THREAD

**Issue by dimkapitonov** [YouROK/TorrServe#77]
On Android TV, when you add server host like `https://torrserver.example.com` application automatically adds default 8090 port in end of line, and then host become like this `https://torrserver.example.com:8090`

**Comment by tsynik** [comment]
> On Android TV, when you add server host like `https://torrserver.example.com` application automatically adds default 8090 port in end of line, and then host become like this `https://torrserver.example.com:8090`

Port is _always_ exists. So, you can define it also for that url (default port is 80 for http and 443 for https(
