### ISSUE TITLE
Client continuously requesting /torrents and /echo when playing

### ISSUE THREAD

**Issue by cocool97** [YouROK/TorrServe#81]
I've found that the Android client is continuously requesting these two endpoints :

- "GET /echo HTTP/1.1" 200 10 
- "POST /torrents HTTP/1.1" 200 63554 

This occurs when video is playing, which is unneeded and saturates the server for nothing.

TorrServer version: `MatriX.125` - Docker version
Torr client - up to date as of today

**Comment by tsynik** [comment]
> This occurs when video is playing, which is unneeded and saturates the server for nothing.

that's expected behaviour
