### ISSUE TITLE
[Feature request] Добавить передачу внешних файлов (ac3\ass\srt\...) в VLC (бывший EXTVLCOPT)

### ISSUE THREAD

**Issue by filimonic** [YouROK/TorrServe#89]
В TS уже есть поддержка тега `#EXTVLCOPT:input-slave=http://...`  в плейлистах.
VLC убрали поддержку EXTVLCOPT в плейлистах из плеера.
Однако под vlc-win (3.0.2) есть возможность передать input-slave в параметрах командной строки в том же формате (как и EXTVLCOPT):
```
vlc.exe 
"http://ts/stream/xxx.mkv?...index=1..." 
":input-slave=http://ts/stream/xxx.ac3?...index=11...#http://ts/stream/xxx.ac3?...index=12...#http://ts/stream/xxx.ass?...index=13#"
```

1) Хотелось бы попросить проверить - имеется ли такая же возможность для Android VLC
2) Если имеется - то предусмотреть в TorrServe возможность передачи для VLC дополнительных input-slave адресов.

**Comment by tsynik** [comment]
Такой возможности в VLC нет
