### ISSUE TITLE
No Issue! just Question how app works..

### ISSUE THREAD

**Issue by Eqfour** [YouROK/TorrServe#92]
Hi, sorry to use this form to ask a maybe stupid question. I habe no idea how the app works. Could anyone explain the detailed steps how to get it working with piratebay for example?
Thanks a lot!!
Greetings

**Comment by tsynik** [comment]
> Could anyone explain the detailed steps how to get it working with piratebay for example?
> Thanks a lot!!

Use torrserver web interface to add magnets / .torrent and get dl/play links from it
