### ISSUE TITLE
[bug] По-умолчанию открывается активити настроек

### ISSUE THREAD

**Issue by filimonic** [YouROK/TorrServe#93]
Устройство: MeCool KM2 Deluxe Plus (Android TV)
Устройство имеет пульт с кнопками Youtube, Netflix, Prime video, Google play
Устройство имеет на борту приложение AppKey для перенастройки этих кнопок

Для приложений Кинопоиск, YouTube, Vimu эти кнопки работают нормально открывается активити, идентичная той, что открывается при запуске приложения "по иконке". С TorrServer - проблема.

**Ожидаемое поведение:** 
Для приложения TorrServe, если на него назначена кнопка через приложение AppKey, при нажатии кнопки на пульте, происходит открытие Torrserve со списком торрентов.

**Фактическое поведение:** 
Для приложения TorrServe, если на него назначена кнопка через приложение AppKey, при нажатии кнопки на пульте, происходит открытие Torrserve с активити "настройки приложения"

![image](https://github.com/YouROK/TorrServe/assets/2893566/9d438119-4d15-4dc7-b0e8-38f1f912ca62)

**Comment by tsynik** [comment]
Not an issue of TorrServe

**Comment by filimonic** [comment]
@tsynik  А мне что-то подсказывает, что это ошибка со стороны TS: `SettingsActivity` запускается от a:main c:default - непонятно зачем. Подозреваю что в этом и есть проблема совсестимости A с B
```
        <activity android:name="ru.yourok.torrserve.ui.activities.main.SettingsActivity"
            android:configChanges="uiMode"
            android:exported="true">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.DEFAULT" />
            </intent-filter>
        </activity>
```

**Comment by tsynik** [comment]
> А мне что-то подсказывает, что это ошибка со стороны TS: `SettingsActivity` запускается от a:main c:default - непонятно зачем. Подозреваю что в этом и есть проблема совсестимости A с B

https://developer.android.com/reference/android/content/Intent#CATEGORY_DEFAULT

для запуска приложения выбираются активности с категорией LAUNCHER или LEANBACK_LAUNCHER на ТВ, и это определяет приложение (AppKey) - все вопросы к нему.

**Comment by filimonic** [comment]
@tsynik Не будете ли вы столь любезны дать apk для пробы. Сам не могу собрать.

**Comment by tsynik** [comment]
> Не будете ли вы столь любезны дать apk для пробы. Сам не могу собрать.

Должен появиться в течение недели на F-Droid: https://f-droid.org/ru/packages/ru.yourok.torrserve/ с тегом MatriX.130.F-Droid

**Comment by filimonic** [comment]
@tsynik Спасибо, в 131 версии все работает.
