### ISSUE TITLE
Aria2 external downloader

### ISSUE THREAD

**Issue by shuvashish76** [YouROK/TorrServe#96]
Similar to [Seal](https://github.com/JunkFood02/Seal) support aria2 as external downloader.
![Screenshot_2024-08-09_18-26-05_1](https://github.com/user-attachments/assets/87873d8f-c534-424d-bea8-fe947916d23c)

https://github.com/aria2/aria2

**Comment by tsynik** [comment]
You can use any - there is Open with context menu for added torrent to open it in external torrent app
