### ISSUE TITLE
Unresolved reference: action_selector

### ISSUE THREAD

**Issue by iospoisson** [YouROK/TorrServe#98]
/ui/fragments/main/settings/SettingsFragment.kt:53:96 Unresolved reference: action_selector
/ui/fragments/main/settings/SettingsFragment.kt:79:38 Unresolved reference: xml
/ui/fragments/main/settings/SettingsFragment.kt:90:69 Unresolved reference: container
/ui/fragments/main/settings/SettingsFragment.kt:97:58 Unresolved reference: container
/ui/fragments/main/settings/SettingsFragment.kt:103:67 Unresolved reference: container
/ui/fragments/main/settings/SettingsFragment.kt:109:32 Unresolved reference: reset_def
/ui/fragments/main/settings/SettingsFragment.kt:113:59 Unresolved reference: player_pref_key
/ui/fragments/main/settings/SettingsFragment.kt:183:56 Unresolved reference: show_battery_save_tv
/ui/fragments/main/settings/SettingsFragment.kt:215:78 Unresolved reference: container
/ui/fragments/main/settings/SettingsFragment.kt:219:48 Unresolved reference: not_found_new_app_update`

**Comment by tsynik** [comment]
it's a question of your SDK setup not source
